-- Task 7 (Digiflazz top-up pilot, final task): one additive schema field.
--
-- Hand-written for the same reason as 20260816020000_add_digiflazz_topup_fields
-- and 20260816030000_add_digiflazz_sync_fields: SQLite's own `ALTER TABLE ADD
-- COLUMN` accepts a plain nullable column fine, and this one carries no
-- NOT NULL/DEFAULT at all, so there is no rebuild-vs-ADD-COLUMN question here
-- — this file just keeps the same hand-authored-migration convention the rest
-- of this pilot's schema changes use.
--
-- Verify with: pnpm run check-migration-drift
--
-- SAFETY: purely additive. `denominations.nickname_check_game_code` is a
-- nullable ADD COLUMN (every existing row gets NULL — no prior denomination
-- had a live nickname check). Null means "no live check for this product",
-- which is the existing (only) behavior, so no backfill is needed.
--
-- DEPLOY: apply with `pnpm exec prisma db push` (see docs/MIGRATIONS.md),
-- then restart order-bot/web/storefront before any code that reads/writes
-- this column runs.

-- AlterTable: denominations — the KokinPay game_code this SKU's title maps
-- to, for the storefront's live nickname-check UX (Task 7). Null = the
-- account field behaves exactly as it does today, no live check offered.
ALTER TABLE "denominations" ADD COLUMN "nickname_check_game_code" TEXT;
