/**
 * Digiflazz supplier client (HTTP + signature) — the auto-fulfillment backend
 * for the "Top Up Game" instant-checkout pilot. Pure: no @app/db dependency
 * (credential resolution belongs to a later task, in @app/db). Mirrors
 * `../payments/tokopay.ts`'s shape.
 *
 * ⚠ ASSUMPTION (flagged, same spirit as tokopay.ts): this is a pilot scaffold,
 *   not a certified integration. The endpoint paths, request/response field
 *   names, and MD5 signature formulas below are modeled on Digiflazz's
 *   publicly documented API shape but have not been verified against a live
 *   account. Verify against the real Digiflazz dashboard/docs before go-live.
 *   Exception: the webhook verifier (`verifyWebhook`) follows Digiflazz's
 *   published webhook spec (HMAC-SHA1 `X-Hub-Signature` over the raw body).
 */
import { createHash, createHmac, timingSafeEqual } from "node:crypto";
import { Decimal } from "../money";
import { logger } from "../logger";
import { fetchWithTimeoutSafe, HTTP_TIMEOUT_MS } from "../http";
import { normalize, extractFeatures, extractTrailingParenthetical } from "../detection";
import { DEFAULT_KNOWLEDGE_BASE } from "../detection/knowledge/defaultVocabulary";

const API_BASE = process.env.DIGIFLAZZ_API_BASE ?? "https://api.digiflazz.com/v1";

export interface DigiflazzCreds {
  username: string;
  apiKey: string;
}

/** The three states Digiflazz reports for a top-up order. Anything the
 * supplier sends that isn't recognized collapses to "Pending" — never assumed
 * delivered, never assumed dead, so a garbled response can't cause a double
 * dispatch or strand a buyer who did pay (same fail-safe-to-"not yet"
 * philosophy as `../payments/paymentStatus.ts`'s `normalizeProviderStatus`). */
export type DigiflazzStatus = "Sukses" | "Pending" | "Gagal";

function normalizeStatus(raw: string | null): DigiflazzStatus {
  const status = (raw ?? "").trim().toLowerCase();
  if (status === "sukses" || status === "success") return "Sukses";
  if (status === "gagal" || status === "failed") return "Gagal";
  return "Pending";
}

/**
 * What went wrong with one Digiflazz HTTP request, so the dispatcher can tell
 * "try again with the same ref id" from "stop and ask a human":
 *  - retryable: `timeout` (the deadline elapsed, before or during the body
 *    read, or an HTTP 408 from a proxy on the way), `network` (fetch itself rejected: DNS, refused, reset, TLS),
 *    `http_5xx`, `http_429` (rate limited), `unparseable` (a body that is not
 *    JSON — typically a proxy error page), and `rejected` (a 2xx JSON reply
 *    without any transaction data — as uncertain as an unparseable body: it
 *    says nothing about whether the purchase exists, so it is retried with
 *    the same ref id rather than given up on).
 *  - permanent: `http_4xx` (any other 4xx except 408 — bad credentials, unknown route,
 *    malformed request; the same request fails the same way again). An
 *    explicit failure Digiflazz reports inside `data` (status Gagal) is not
 *    an error at all — createTransaction returns it and the caller's Gagal
 *    path handles it.
 */
export type DigiflazzRequestErrorKind =
  | "timeout"
  | "network"
  | "http_5xx"
  | "http_429"
  | "http_4xx"
  | "unparseable"
  | "rejected";

export function isRetryableDigiflazzErrorKind(kind: DigiflazzRequestErrorKind): boolean {
  return kind !== "http_4xx";
}

/** Maps a non-2xx HTTP status to its error kind (see DigiflazzRequestErrorKind).
 * HTTP 408 is a `timeout`, not a permanent 4xx: it is usually generated by a
 * proxy after the request may already have reached Digiflazz, so it is retried
 * with the same ref id like any other timeout. */
export function classifyDigiflazzHttpStatus(status: number): DigiflazzRequestErrorKind {
  if (status === 408) return "timeout";
  if (status === 429) return "http_429";
  if (status >= 400 && status < 500) return "http_4xx";
  return "http_5xx";
}

/**
 * The error `getPriceList`/`createTransaction` throw for every request
 * failure. Still a plain `Error` with the same static, credential-free
 * message as before (callers that only read `.message` see no change), plus
 * a `kind`, whether retrying with the same ref id can help, and the HTTP
 * status when there was one. It never carries the original error or a
 * `cause` — that is where Node's fetch attaches the API-key-bearing request.
 */
export class DigiflazzRequestError extends Error {
  readonly kind: DigiflazzRequestErrorKind;
  readonly retryable: boolean;
  readonly httpStatus: number | null;

  constructor(message: string, kind: DigiflazzRequestErrorKind, httpStatus: number | null = null) {
    super(message);
    this.name = "DigiflazzRequestError";
    this.kind = kind;
    this.retryable = isRetryableDigiflazzErrorKind(kind);
    this.httpStatus = httpStatus;
  }
}

/**
 * POST a Digiflazz endpoint whose JSON body carries the username/API key, and
 * return its parsed JSON body. Every failure mode of the raw `fetch()` call is
 * caught HERE, inside this single choke point, via `fetchWithTimeoutSafe`
 * (`@app/core/http`): it rethrows a new `Error` built from a static,
 * credential-free string, whether `fetch()` itself rejected (DNS failure,
 * connection refused, aborted, TLS error, …: Node's `fetch` sometimes attaches
 * the failed request — including the body it was sent with — to `err.cause`,
 * which a naive `logger.error({ err })` downstream would serialize whole,
 * echoing the API key straight back into logs) or the deadline (`timeoutMs`)
 * elapsed first. `res.json()` gets the same static-message treatment below on
 * a malformed body. The existing `!res.ok` branch keeps its own static-message
 * throw. Both `getPriceList` and `createTransaction` share this one guarantee.
 * Every throw is a DigiflazzRequestError carrying its kind; the messages are
 * the same static strings as before.
 */
async function fetchDigiflazzJson(
  url: string,
  init: Omit<RequestInit, "signal">,
  errorPrefix: string,
  timeoutMs: number,
): Promise<Record<string, unknown>> {
  let res: Response;
  try {
    res = await fetchWithTimeoutSafe(url, { ...init, timeoutMs }, errorPrefix); // never log init.body — it carries the API key
  } catch (err) {
    // fetchWithTimeoutSafe already replaced the original error with one of two
    // static messages; rebuild it as a typed error from that message alone.
    const timedOut = err instanceof Error && err.message === `${errorPrefix} timed out`;
    throw new DigiflazzRequestError(
      `${errorPrefix} ${timedOut ? "timed out" : "network error"}`,
      timedOut ? "timeout" : "network",
    );
  }
  if (!res.ok) {
    // never log init.body — it carries the API key
    throw new DigiflazzRequestError(`${errorPrefix} HTTP ${res.status}`, classifyDigiflazzHttpStatus(res.status), res.status);
  }
  try {
    return (await res.json()) as Record<string, unknown>;
  } catch (err) {
    // AbortSignal.timeout stays attached to the response body in undici, so a
    // peer that sends headers and then stalls the body makes res.json()
    // reject with this same TimeoutError shape (http.ts) — distinguish that
    // from a genuinely malformed body so the caller isn't told the supplier
    // sent garbage when it actually just hung.
    if (err instanceof Error && err.name === "TimeoutError") {
      throw new DigiflazzRequestError(`${errorPrefix} response body read timed out`, "timeout"); // never log init.body — it carries the API key
    }
    throw new DigiflazzRequestError(`${errorPrefix} returned an unparseable response`, "unparseable"); // never log init.body — it carries the API key
  }
}

function jsonPost(payload: Record<string, unknown>): Omit<RequestInit, "signal"> {
  return {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify(payload),
  };
}

export interface DigiflazzPriceListItem {
  buyerSkuCode: string;
  productName: string;
  category: string | null;
  brand: string | null;
  type: string | null;
  price: Decimal;
  buyerProductStatus: boolean;
  sellerProductStatus: boolean;
  /** Null when the supplier reports unlimited/no stock figure. */
  stock: number | null;
}

/**
 * Fetch Digiflazz's full prepaid SKU/price list for this account.
 *
 * ⚠ ASSUMPTION (flagged, same as the rest of this client): the `cmd:
 *   "prepaid"` request shape and the `sign = md5(username + apiKey +
 *   "pricelist")` formula follow Digiflazz's public docs. Verify against the
 *   live dashboard before go-live.
 */
export async function getPriceList(creds: DigiflazzCreds): Promise<DigiflazzPriceListItem[]> {
  const sign = createHash("md5").update(`${creds.username}${creds.apiKey}pricelist`).digest("hex");
  const body = (await fetchDigiflazzJson(
    `${API_BASE}/price-list`,
    jsonPost({ cmd: "prepaid", username: creds.username, sign }),
    "Digiflazz price list",
    HTTP_TIMEOUT_MS.gatewayRead, // catalog sync poll — the next tick retries if this is slow
  )) as { data?: unknown };
  const rows = Array.isArray(body.data) ? body.data : [];
  const items: DigiflazzPriceListItem[] = [];
  let skipped = 0;
  for (const raw of rows) {
    const item = toPriceListItem(raw as Record<string, unknown>);
    if (item === null) {
      skipped++;
      continue;
    }
    items.push(item);
  }
  if (skipped > 0) {
    logger.warn(`Digiflazz price list: skipped ${skipped} row(s) with an invalid or non-positive price`);
  }
  return items;
}

/** Returns null (row skipped by the caller) when the supplier's price for
 * this row is missing, unparseable, non-finite, or not strictly positive —
 * see `toDecimalOrNull`. Never returns an item with a placeholder price. */
function toPriceListItem(d: Record<string, unknown>): DigiflazzPriceListItem | null {
  const price = toDecimalOrNull(d.price);
  if (price === null) return null;
  return {
    buyerSkuCode: str(d.buyer_sku_code) ?? "",
    productName: str(d.product_name) ?? "",
    category: str(d.category),
    brand: str(d.brand),
    type: str(d.type),
    price,
    buyerProductStatus: d.buyer_product_status === true,
    sellerProductStatus: d.seller_product_status === true,
    stock: typeof d.stock === "number" && Number.isFinite(d.stock) ? d.stock : null,
  };
}

/**
 * Extract a region code from the trailing parenthetical of a Digiflazz product name.
 *
 * Uses `extractTrailingParenthetical` (`@app/core/detection`, shared with
 * `detection/features.ts`'s own use of the same "trailing (...)" shape) to
 * match a trailing parenthetical suffix, trimming and returning the captured
 * text, or `null` if no match or the match is denylisted.
 *
 * **Denylist guard**: Not every trailing parenthetical is a region — Digiflazz also uses
 * parens for delivery-speed annotations like `"(Instant)"`, `"(1-3 Menit)"`, or
 * `"(Proses Cepat)"`. The denylist decision is delegated to the Detection Engine's
 * `extractFeatures()` (`@app/core/detection`), which classifies the same trailing
 * parenthetical against the Knowledge layer's `noise`-category tokens (`instant`,
 * `proses cepat` — `detection/knowledge/defaultVocabulary.ts`) plus one hardcoded
 * structural duration-range pattern (`N N menit|jam|hari`, post-`normalize()` shape —
 * see `features.ts`'s own comment).
 *
 * **Static vocabulary only — this does NOT see DB-added `DetectionToken` rows.**
 * This wrapper calls `extractFeatures()` against the frozen `DEFAULT_KNOWLEDGE_BASE`
 * (the static seed vocabulary baked into `detection/knowledge/defaultVocabulary.ts`),
 * not the DB-backed knowledge base `loadKnowledgeBase(db)`
 * (`packages/db/src/crud/detectionKnowledge.ts`) builds by reading
 * `db.detectionToken.findMany()`. An admin who adds a `noise`-category
 * `DetectionToken` row via the admin panel will see it take effect in
 * `loadKnowledgeBase`-driven paths (detection runs, catalog index build) but
 * NOT here — this function, `stripRegionSuffix`, and `digiflazzGroupKey` are
 * synchronous and pure, and live in `@app/core`, which cannot import `@app/db`
 * to reach the database; there is no way for them to read admin-added rows
 * without breaking that boundary. Extending the denylist for THESE THREE
 * FUNCTIONS specifically therefore means editing `defaultVocabulary.ts`'s
 * noise tokens directly — a code/data change requiring a deploy — not an
 * admin-panel edit.
 *
 * A denylisted match always returns `null`, never a false split. The returned string
 * (when non-null) is re-sliced from the ORIGINAL, non-normalized `productName` — not
 * `extractFeatures().parentheticalSuffix` — because `normalize()` lowercases, and this
 * function's contract (see the test suite) is to return the captured text in its
 * original casing, only trimmed.
 */
export function parseProductRegion(productName: string): string | null {
  const match = extractTrailingParenthetical(productName);
  if (!match) return null;

  const captured = match.captured.trim();

  const isDenylisted =
    extractFeatures(normalize(productName), DEFAULT_KNOWLEDGE_BASE).parentheticalSuffix === null;
  if (isDenylisted) return null;

  return captured;
}

/**
 * Strip a region suffix from a Digiflazz product name if present.
 *
 * Uses `parseProductRegion` internally to determine whether the trailing
 * parenthetical is a region. Only strips if `parseProductRegion` returns
 * non-null, ensuring the two functions never disagree about what counts
 * as a region.
 *
 * Input with no region suffix passes through completely unchanged (same
 * string, same whitespace).
 *
 * Never returns an empty (or whitespace-only) string: a productName that is
 * ENTIRELY a parenthetical (e.g. `"(Indonesia)"`, nothing before it) strips
 * down to `""`, which would otherwise become an empty `name`/`durationLabel`
 * and an empty base for `ensureUniqueSlug` — treat that case as "not safely
 * strippable" and return the original, unstripped string instead.
 */
export function stripRegionSuffix(productName: string): string {
  if (parseProductRegion(productName) === null) {
    return productName;
  }
  // parseProductRegion returning non-null above already proved
  // extractTrailingParenthetical matches productName, so match is non-null
  // here. Slicing up to the match's start index removes the trailing
  // parenthetical plus any whitespace before it — equivalent to
  // `productName.replace(TRAILING_PARENTHETICAL, "")`, since that pattern is
  // anchored to the end of the string ($).
  const match = extractTrailingParenthetical(productName)!;
  const stripped = productName.slice(0, match.index);
  if (stripped.trim() === "") {
    return productName;
  }
  return stripped;
}

/**
 * Generate a grouping key from a Digiflazz brand and product name.
 *
 * Returns an object with:
 * - `brand`: the input brand unchanged
 * - `region`: the result of `parseProductRegion(productName)` (null if no region)
 * - `displayName`: if a region is present, `"${brand} (${region})"`, otherwise just `brand`
 *
 * The `displayName` is the value later used as both `Product.name` and
 * `Product.digiflazzBrand` during catalog sync. This function must be deterministic
 * and is depended on by downstream grouping and migration logic.
 */
export function digiflazzGroupKey(
  brand: string,
  productName: string,
): { brand: string; region: string | null; displayName: string } {
  const region = parseProductRegion(productName);
  return {
    brand,
    region,
    displayName: region ? `${brand} (${region})` : brand,
  };
}

export interface DigiflazzTransactionResult {
  refId: string;
  status: DigiflazzStatus;
  /** Serial number / receipt, present once status is "Sukses". */
  sn: string | null;
  /** Supplier-provided detail — success confirmation text, pending notice, or
   * failure reason, depending on `status`. */
  message: string | null;
  price: Decimal | null;
}

/**
 * Place a top-up order (deposit — prepaid). `refId` is Digiflazz's
 * idempotency key: a repeat call with the same `refId` returns the existing
 * transaction rather than creating a new one.
 *
 * ⚠ ASSUMPTION (flagged, same as the rest of this client): the request shape
 *   and the `sign = md5(username + apiKey + refId)` formula follow Digiflazz's
 *   public docs. Verify against the live dashboard before go-live.
 */
export async function createTransaction(
  creds: DigiflazzCreds,
  args: { refId: string; buyerSkuCode: string; customerNo: string },
): Promise<DigiflazzTransactionResult> {
  const sign = createHash("md5").update(`${creds.username}${creds.apiKey}${args.refId}`).digest("hex");
  const body = (await fetchDigiflazzJson(
    `${API_BASE}/transaction`,
    jsonPost({
      username: creds.username,
      buyer_sku_code: args.buyerSkuCode,
      customer_no: args.customerNo,
      ref_id: args.refId,
      sign,
    }),
    "Digiflazz transaction",
    HTTP_TIMEOUT_MS.gatewayWrite, // a human is waiting at checkout for this to resolve
  )) as { data?: Record<string, unknown> };
  const d = body.data;
  if (!d) {
    // Digiflazz answers every transaction it processed with a `data` object
    // (even a Gagal); a 2xx without one says nothing about whether the
    // purchase exists, so it is retryable (same ref id), like an unparseable body.
    throw new DigiflazzRequestError("Digiflazz transaction rejected: missing data in response", "rejected");
  }
  return {
    refId: str(d.ref_id) ?? args.refId,
    status: normalizeStatus(str(d.status)),
    sn: str(d.sn),
    message: str(d.message),
    price: d.price != null ? toDecimalOrNull(d.price) : null,
  };
}

export interface DigiflazzCallback {
  refId: string;
  status: DigiflazzStatus;
  sn: string | null;
  message: string | null;
  price: Decimal | null;
}

/** `sha1=` followed by exactly 40 hex digits (a SHA-1 digest), any case. */
const HUB_SIGNATURE_RE = /^sha1=([0-9a-f]{40})$/i;

/**
 * Verify a Digiflazz webhook delivery and normalize it. Returns null on any
 * failure; never throws.
 *
 * This is Digiflazz's documented scheme (developer.digiflazz.com/api/buyer/
 * webhook): the request carries `X-Hub-Signature: sha1=<hex>`, the HMAC-SHA1
 * of the RAW request body keyed by the webhook secret configured in the
 * Digiflazz dashboard, and the transaction sits under a top-level `data`
 * object (`data.ref_id`, `data.status`, `data.sn`, `data.message`,
 * `data.price`). It replaces an invented `md5(refId + ":" + apiKey)` body
 * field that Digiflazz never sends, which made every real webhook fail.
 *
 * The HMAC is computed over the exact bytes received, never over re-serialized
 * JSON (a `1.50` vs `1.5` or whitespace difference would change the digest),
 * so callers must hand over the raw body. The comparison is constant-time on
 * the decoded 20-byte digests. There is no unsigned path: a missing secret, a
 * missing header, or a header without the `sha1=` prefix is a rejection.
 * The body is only parsed AFTER the signature checks out, so nothing from an
 * unverified request — in particular its reference — is ever read or logged
 * (Task B3e: those are attacker-controlled bytes that could forge log lines).
 */
export function verifyWebhook(
  webhookSecret: string,
  rawBody: Buffer | string,
  signatureHeader: string | undefined,
): DigiflazzCallback | null {
  const result = inspectWebhook(webhookSecret, rawBody, signatureHeader);
  if (result.ok) return result.callback;
  if (result.reason === "no_reference") {
    // inspectWebhook leaves this case unlogged so a caller can treat it as a
    // signed ping; this null-returning wrapper still reports it as a rejection.
    logger.warn("Rejected a correctly signed Digiflazz webhook because its body has no data.ref_id");
  }
  return null;
}

/** Why inspectWebhook did not return a callback. `no_reference` is the only
 * reason that comes from a request whose signature DID verify and whose body
 * is JSON — Digiflazz test/ping deliveries carry no transaction — so a caller
 * may answer it with a plain 200 instead of a 403. */
export type DigiflazzWebhookRejection = "no_secret" | "bad_signature" | "invalid_body" | "no_reference";

export type DigiflazzWebhookInspection =
  | { ok: true; callback: DigiflazzCallback }
  | { ok: false; reason: DigiflazzWebhookRejection };

/**
 * verifyWebhook with the reason for a rejection (same checks, same order, same
 * constant-time comparison; the body is still only parsed after the signature
 * verified). Logs a warning for every rejection except `no_reference`, which
 * is left to the caller: a correctly signed body without `data.ref_id` is a
 * test/ping event, not an attack, and deserves an info line, not a warning.
 */
export function inspectWebhook(
  webhookSecret: string,
  rawBody: Buffer | string,
  signatureHeader: string | undefined,
): DigiflazzWebhookInspection {
  if (!webhookSecret) {
    logger.warn("Rejected a Digiflazz webhook because no webhook secret is configured, so its signature cannot be checked");
    return { ok: false, reason: "no_secret" };
  }
  const match = HUB_SIGNATURE_RE.exec((signatureHeader ?? "").trim());
  if (!match) {
    logger.warn(
      "Rejected a Digiflazz webhook because its X-Hub-Signature header was missing or not in the sha1=<hex> form — the request body was not read",
    );
    return { ok: false, reason: "bad_signature" };
  }
  const received = Buffer.from(match[1]!, "hex");
  const expected = createHmac("sha1", webhookSecret).update(rawBody).digest();
  if (received.length !== expected.length || !timingSafeEqual(received, expected)) {
    logger.warn(
      "Rejected a Digiflazz webhook whose signature did not match its body — the body and its reference are not logged because they are unverified input",
    );
    return { ok: false, reason: "bad_signature" };
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(typeof rawBody === "string" ? rawBody : rawBody.toString("utf8"));
  } catch {
    logger.warn("Rejected a correctly signed Digiflazz webhook because its body is not valid JSON");
    return { ok: false, reason: "invalid_body" };
  }
  const data =
    parsed && typeof parsed === "object" ? (parsed as { data?: unknown }).data : undefined;
  if (!data || typeof data !== "object" || Array.isArray(data)) return { ok: false, reason: "no_reference" };
  const d = data as Record<string, unknown>;
  const refId = str(d.ref_id);
  if (!refId) return { ok: false, reason: "no_reference" };

  return {
    ok: true,
    callback: {
      refId,
      status: normalizeStatus(str(d.status)),
      sn: str(d.sn),
      message: str(d.message),
      price: d.price != null ? toDecimalOrNull(d.price) : null,
    },
  };
}

function str(v: unknown): string | null {
  if (typeof v === "string" && v.trim()) return v.trim();
  if (typeof v === "number" && Number.isFinite(v)) return String(v);
  return null;
}

/** Parses a supplier-supplied price. Returns null — not a placeholder
 * Decimal — when the value is missing, unparseable, non-finite (NaN or
 * ±Infinity; decimal.js accepts both as valid `Decimal`s by default, so this
 * must be checked explicitly via `isFinite()`), or not strictly positive: a
 * supplier cost of zero or negative is never legitimate for this shop's
 * catalog.
 *
 * Minor 1 (final whole-branch review, 2026-08-21): this non-positive
 * rejection was added (Task 9) for the price-list parsing path (toPriceListItem
 * above) but this is one shared helper used by all three call sites —
 * `createTransaction`'s and `verifyWebhook`'s `.price` fields are parsed
 * through it too, so they now silently reject a zero/negative price the same
 * way. Harmless today: no consumer currently reads `.price` off either of
 * those two results — but be aware this helper's behavior is shared, not
 * price-list-specific, before adding a new consumer of either. */
function toDecimalOrNull(v: unknown): Decimal | null {
  if (v == null) return null;
  try {
    const d = new Decimal(String(v));
    if (!d.isFinite() || d.lessThanOrEqualTo(0)) return null;
    return d;
  } catch {
    return null;
  }
}
